
import 'dotenv/config';
import fetch from 'node-fetch';
import { db } from './server/database.js';
import jwt from 'jsonwebtoken';
import { JWT_SECRET } from './server/middleware/auth.js';

// 1. Get Agent User
const agent = db.prepare("SELECT * FROM users WHERE email = 'agent@gmail.com'").get();
if (!agent) {
    console.error("Agent not found!");
    process.exit(1);
}

console.log("Found Agent:", agent.email, agent.role);

// 2. Create Token
const token = jwt.sign({ id: agent.user_id, role: agent.role }, JWT_SECRET, { expiresIn: '1h' });

// 3. Make POST Request
const payload = {
    title: "Test Package From Script",
    destination: "Test City",
    price: 5000,
    duration: "3 Days",
    available_slots: 10,
    description: "Autogenerated test package"
};

console.log("Sending payload:", payload);

try {
    const res = await fetch('http://localhost:3000/api/packages', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(payload)
    });

    const data = await res.json();
    console.log("Status:", res.status);
    console.log("Response:", data);

} catch (err) {
    console.error("Fetch failed:", err);
}
